version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "scrobble-proxy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7bh71zv8teud"
s3_prefix = "scrobble-proxy"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
