AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  scrobble-proxy-function

  Sample SAM Template for scrobble-proxy-function

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ScrobbleProxyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        ScrobbleProxy:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /scrobble
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ScrobbleProxyApi:
    Description: "API Gateway endpoint URL for Prod stage for Scrobble Proxy function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/scrobble/"
  ScrobbleProxyFunction:
    Description: "Scrobble Proxy Lambda Function ARN"
    Value: !GetAtt ScrobbleProxyFunction.Arn
  ScrobbleProxyFunctionIamRole:
    Description: "Implicit IAM Role created for Scrobble Proxy function"
    Value: !GetAtt ScrobbleProxyFunctionRole.Arn
