AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  scrobble-proxy

  SAM Template for a custom Spotify scrobbler

Globals:
  Function:
    Timeout: 3

Resources:
  ScrobbleProxyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.scrobble
      Runtime: nodejs14.x
      Events:
        ScrobbleProxy:
          Type: Api
          Properties:
            Path: /scrobble
            Method: post

Outputs:
  ScrobbleProxyApi:
    Description: "API Gateway endpoint URL for Prod stage for Scrobble Proxy function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/scrobble/"
  ScrobbleProxyFunction:
    Description: "Scrobble Proxy Lambda Function ARN"
    Value: !GetAtt ScrobbleProxyFunction.Arn
  ScrobbleProxyFunctionIamRole:
    Description: "Implicit IAM Role created for Scrobble Proxy function"
    Value: !GetAtt ScrobbleProxyFunctionRole.Arn
